training:
  # Количество эпох обучения модели.
  # Epoch — это полное прохождение всей тренировочной выборки через модель.
  # Увеличение числа эпох может улучшить точность модели, но может привести к переобучению.
  epochs: 20

  # Размер батча — количество примеров, которые модель будет обрабатывать за один шаг.
  # Большие значения могут ускорить обучение, но требуют больше памяти. Маленькие — дают более стабильные градиенты.
  batch_size: 64

  # Скорость обучения (learning rate) — это важный гиперпараметр, который определяет, насколько сильно
  # обновляются веса модели при каждом шаге.
  # Маленькое значение может замедлить обучение, слишком большое — привести к нестабильности.
  learning_rate: 0.001

paths:
  train_data_dir: "datasets/train"
  test_data_dir: "datasets/test"
  model_save_path: "output/model.bson"
  image_path: "src/testing/image.png"
